"""Create factory, simulation, and blueprint tables.

Revision ID: be0d5f18f01b
Revises: f64eead571ed
Create Date: 2026-08-18 15:50:19.236919
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'be0d5f18f01b'
down_revision: Union[str, None] = 'f64eead571ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('fork_count', sa.Integer(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_owner_id'), 'blueprints', ['owner_id'], unique=False)
    op.create_table('factories',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('grid_size_m', sa.Float(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_owner_id'), 'factories', ['owner_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('elapsed_sim_sec', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=16), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_factory_id'), 'activity_events', ['factory_id'], unique=False)
    op.create_table('blueprint_forks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('blueprint_id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_forks_blueprint_id'), 'blueprint_forks', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_forks_factory_id'), 'blueprint_forks', ['factory_id'], unique=False)
    op.create_index(op.f('ix_blueprint_forks_owner_id'), 'blueprint_forks', ['owner_id'], unique=False)
    op.create_table('blueprint_stars',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('blueprint_id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'owner_id', name='uq_blueprint_star_owner')
    )
    op.create_index(op.f('ix_blueprint_stars_blueprint_id'), 'blueprint_stars', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_stars_owner_id'), 'blueprint_stars', ['owner_id'], unique=False)
    op.create_table('factory_objects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('floor_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_ref', sa.Text(), nullable=True),
    sa.Column('transform_x', sa.Float(), nullable=False),
    sa.Column('transform_z', sa.Float(), nullable=False),
    sa.Column('transform_rotation_y', sa.Integer(), nullable=False),
    sa.Column('footprint_width', sa.Float(), nullable=False),
    sa.Column('footprint_depth', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_objects_factory_id'), 'factory_objects', ['factory_id'], unique=False)
    op.create_index(op.f('ix_factory_objects_floor_id'), 'factory_objects', ['floor_id'], unique=False)
    op.create_index(op.f('ix_factory_objects_kind'), 'factory_objects', ['kind'], unique=False)
    op.create_table('floors',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'level', name='uq_floor_factory_level')
    )
    op.create_index(op.f('ix_floors_factory_id'), 'floors', ['factory_id'], unique=False)
    op.create_table('inventory_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('location_type', sa.String(length=32), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('reserved_outbound_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_inbound_capacity', sa.Integer(), nullable=False),
    sa.Column('infinite_supply', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'location_id', 'item_id', name='uq_inventory_factory_location_item')
    )
    op.create_index(op.f('ix_inventory_records_factory_id'), 'inventory_records', ['factory_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_item_id'), 'inventory_records', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_location_id'), 'inventory_records', ['location_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('item_model_id', sa.String(length=128), nullable=False),
    sa.Column('model_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('mass_kg', sa.Float(), nullable=False),
    sa.Column('max_stack_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', name='uq_item_factory_code')
    )
    op.create_index(op.f('ix_items_factory_id'), 'items', ['factory_id'], unique=False)
    op.create_table('metric_samples',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('elapsed_sim_sec', sa.Float(), nullable=False),
    sa.Column('throughput_per_min', sa.Float(), nullable=False),
    sa.Column('work_in_progress', sa.Integer(), nullable=False),
    sa.Column('finished_goods', sa.Integer(), nullable=False),
    sa.Column('machine_a_utilization', sa.Float(), nullable=False),
    sa.Column('machine_b_utilization', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_samples_factory_id'), 'metric_samples', ['factory_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processing_time_sec', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factory_id', 'code', name='uq_recipe_factory_code')
    )
    op.create_index(op.f('ix_recipes_factory_id'), 'recipes', ['factory_id'], unique=False)
    op.create_table('simulation_states',
    sa.Column('factory_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('elapsed_sim_sec', sa.Float(), nullable=False),
    sa.Column('tick_count', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('accumulated_unstepped_sec', sa.Float(), nullable=False),
    sa.Column('machine_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agv_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('drone_runtime', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transit_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warehouse_dispatch_cooldown_sec_by_port', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_feed_cooldown_sec', sa.Float(), nullable=False),
    sa.Column('next_transit_sequence', sa.Integer(), nullable=False),
    sa.Column('next_metric_sample_at_sec', sa.Float(), nullable=False),
    sa.Column('production_events_sec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_transport_durations_sec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_finished', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('factory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_states')
    op.drop_index(op.f('ix_recipes_factory_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_metric_samples_factory_id'), table_name='metric_samples')
    op.drop_table('metric_samples')
    op.drop_index(op.f('ix_items_factory_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_inventory_records_location_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_item_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_factory_id'), table_name='inventory_records')
    op.drop_table('inventory_records')
    op.drop_index(op.f('ix_floors_factory_id'), table_name='floors')
    op.drop_table('floors')
    op.drop_index(op.f('ix_factory_objects_kind'), table_name='factory_objects')
    op.drop_index(op.f('ix_factory_objects_floor_id'), table_name='factory_objects')
    op.drop_table('factory_objects')
    op.drop_index(op.f('ix_blueprint_stars_owner_id'), table_name='blueprint_stars')
    op.drop_index(op.f('ix_blueprint_stars_blueprint_id'), table_name='blueprint_stars')
    op.drop_table('blueprint_stars')
    op.drop_index(op.f('ix_blueprint_forks_owner_id'), table_name='blueprint_forks')
    op.drop_index(op.f('ix_blueprint_forks_factory_id'), table_name='blueprint_forks')
    op.drop_index(op.f('ix_blueprint_forks_blueprint_id'), table_name='blueprint_forks')
    op.drop_table('blueprint_forks')
    op.drop_index(op.f('ix_activity_events_factory_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_factories_owner_id'), table_name='factories')
    op.drop_table('factories')
    op.drop_index(op.f('ix_blueprints_owner_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
